### ISSUE TITLE
Investigate Rev Robotics Spark Max motor controller

### ISSUE THREAD

**Issue by sonicbhoc** [Team-Paragon-571/Bradley#18]

**Comment by fishyfishfish55** [comment]
Found [SPARK MAX](https://docs.revrobotics.com/sparkmax/specifications) [examples](https://github.com/REVrobotics/SPARK-MAX-Examples/tree/master/Java) and [SPARK MAX docs](https://docs.revrobotics.com/sparkmax/gs-sm). Created [example repo](https://github.com/fishyfishfish55/Velocity-Closed-Loop-Control) to further explore closed loop control.
