### ISSUE TITLE
Add profiles for practice and real robot operation in Smart Dashboard

### ISSUE THREAD

**Issue by sonicbhoc** [Team-Paragon-571/Bradley#27]
The practice robot will only have 2 Talon drive motors; The real robot will have 4. A control should be added to the Smart Dashboard to switch modes, and defensive code should be written to prevent the robot from crashing if the wrong profile is selected by mistake.

This task could also be completed with build switches, but that may be more time consuming.

**Comment by sonicbhoc** [comment]
Alternatives:
* Poll CAN at startup and handle the case where the second set of motors are missing
* Base code on the names of the devices

**Comment by fishyfishfish55** [comment]
Closed issue. Reason: obsolete. Build team is adding two additional motors to the practice robot.
