### ISSUE TITLE
Implement ball intake and map to 'a' button on XBoxController.

### ISSUE THREAD

**Issue by fishyfishfish55** [Team-Paragon-571/Bradley#53]
1. aButton.whenPressed:
    - [x] drop intake arms until limit reached

2. aButton.whileHeld:
    - [x] start intake motor 
         - [ ] Determine best speed;
    - [x] Start hopper motor
        - [ ] Determine best speed;
    - [x] (optional) Stop motors when hopper sensors trip

3. aButton.whenReleased:
    - [x] raise intake arms until upper limit is reached

 (time permitting we can integrate hopper sensors.)

**Comment by sonicbhoc** [comment]
I'd say to also make sure the motors don't run until both arm limit switches are pressed, if that is possible.

**Comment by sonicbhoc** [comment]
We might want to consider making the intake to a toggle.

**Comment by fishyfishfish55** [comment]
Closed. Reason: Merged
