### ISSUE TITLE
Explore SlewRateLimiter to smooth acceleration.

### ISSUE THREAD

**Issue by kramoniker** [Team-Paragon-571/Bradley#58]
Introduce SlewRateLimiter filter as a smartdashboard variable to tune forward acceleration.

https://docs.wpilib.org/en/stable/docs/software/advanced-controls/filters/slew-rate-limiter.html#slew-rate-limiter

**Comment by fishyfishfish55** [comment]
SlewRateLimiter explored. Verdict: Unsuitable for our purposes. Although smoothing is a nice idea, it made controls unusually unresponsive.
