### ISSUE TITLE
Add intake break beam sensor controller

### ISSUE THREAD

**Issue by sonicbhoc** [Team-Paragon-571/Bradley#8]

**Comment by sonicbhoc** [comment]
Requirements:
1. Motor on; no beam tripped
2. First beam break; start indexer
3. Second/third beam break; stop both motors and increment ball counter

**Comment by fishyfishfish55** [comment]
WPILib DigitalInput documentation: https://docs.wpilib.org/en/stable/docs/software/hardware-apis/sensors/digital-inputs-software.html?highlight=DigitalInput#the-digitalinput-class
